def handle(exception):
    assert exception is None, "Checker caught hold violations when it shouldn't have"
